template = "https://github.com/giellalt/template-lang-und"
rev_id = 331
template_sha = "8cacf2c4546a4e46881bd306e8c347aa8b1ae938"

[replacements]
__GLOTTOLOG_ID__ = "tavr1235"
__REPO__ = "lang-rmu-x-testing"
__UND2C__ = "rmu"
__UNDEFINED__ = "Tavringer Romani"
__UND__ = "rmu"
