template = "https://github.com/giellalt/template-lang-und"
rev_id = 318
template_sha = "71a1af4cb1cb80e9b86b2e9d1c090f473b0d8270"

[replacements]
__GLOTTOLOG_ID__ = "tavr1235"
__REPO__ = "lang-rmu-x-testing"
__UND2C__ = "rmu"
__UNDEFINED__ = "Tavringer Romani"
__UND__ = "rmu"
