template = "https://github.com/giellalt/template-lang-und"
rev_id = 287
template_sha = "15a8cf1917db1d48c56f7254ed58b4e74a6fcd9c"

[replacements]
__GLOTTOLOG_ID__ = "tavr1235"
__REPO__ = "lang-rmu-x-testing"
__UND2C__ = "rmu"
__UNDEFINED__ = "Tavringer Romani"
__UND__ = "rmu"
